### ISSUE TITLE
Measure not exporting nested Symbols (typography)

### ISSUE THREAD

**Issue by tundiszasz** [utom/sketch-measure#401]
A lot of nested symbols (including varying typography, buttons etc) aren't showing up in the measure export.

Is there something I'm doing wrong here?

**Comment by nzmb** [comment]
Duplicated with #400 fixed with update 2.7.2

**Comment by jjaszkin** [comment]
I still have this problem - I need to detach all symbols to get them measurable in html preview.
Sketch version: 49.3, MacOS: HighSierra 10.13.3 (17D47)
