### ISSUE TITLE
Please update for Sketch v52

### ISSUE THREAD

**Issue by Huweiii** [utom/sketch-measure#482]
Please update for Sketch v52. Thank you very much!

**Comment by naresh-srirangampalle** [comment]
Please update. It is very difficult to work with out this plug-in.

**Comment by ellunium** [comment]
@Huweiii:

I gave it a try to fix it here: 
[Fix for Sketch v52 and v52.1 - With Inspector / Mark Property (and more) working](https://github.com/utom/sketch-measure/pull/474)

You can get the file from the fork. Give it a try and see if it works for you:
[Repository (Fork)](https://github.com/ellunium/sketch-measure)
[Download the zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)

I hope it helps 😊

**Comment by naresh-srirangampalle** [comment]
Thank you so much team.

It’s working fine.


Best Regards
Naresh S
________________________________
Naresh S | Sr. Visual Designer - CTIC | [24]7.ai | Mobile: +91 99860 54542 | www.247.ai

**Comment by aptx4869zoe** [comment]
> @Huweiii:
> 
> I gave it a try to fix it here:
> [Fix for Sketch v52 and v52.1 - With Inspector / Mark Property (and more) working](https://github.com/utom/sketch-measure/pull/474)
> 
> You can get the file from the fork. Give it a try and see if it works for you:
> [Repository (Fork)](https://github.com/ellunium/sketch-measure)
> [Download the zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)
> 
> I hope it helps 😊

wow,thanks a lot, it's really helpful

**Comment by luxlogica** [comment]
Please note, that there are now **11 Issues** that basically say the same thing: Sketch Measure is broken with the latest releases of Sketch. 

Posting yet another issue saying exactly the same thing IS NOT HELPFUL. You can simply add your own experience, or frustration, by leaving a comment in one of the *many* existing issues.

These issues are #468, #469, #471, #472, #473, #475, #476, #477, #479, #481, and this one.

Sketch Measure developers: please review the fix from @ellunium, which might enable you to close these 11 issues at once.

**Comment by kathrynl16** [comment]
I'm now getting the following error even with the latest update. 
![screen shot 2018-10-12 at 11 55 12 am](https://user-images.githubusercontent.com/22449028/46880094-c0423680-ce15-11e8-8637-ea5a29b0eef1.png)

**Comment by ellunium** [comment]
@kathrynl16: Thanks for reporting! 

Could you please give me more details about it?

- What are you trying to do?
- What would expect to happen?
- What actually happens now?

Also, if you can create a small example sketch file and put in a zip for me to test, that would be great :) 
By the way, did you try uninstalling, restarting sketch and reinstalling latest?

[Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)

**Comment by ellunium** [comment]
@kathrynl16: Could you please give it a try to the latest version?

I've added support for Library styles and a check to prevent the error you reported (https://github.com/utom/sketch-measure/pull/474/commits/65fe50b604ecc72309afb01c38674cc79fcfa8c4)

Remember to uninstall, restart sketch and install again.

[Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)

**Comment by kathrynl16** [comment]
Hi @ellunium Thanks for the prompt response! I'm still getting the same issue. Might be an issue on my end. I download the update and on opening Sketch preferences from the Splash page (before opening a file) I can see version 2.7.6 is installed. However when I open a file and reopen the preferences, the version has changed to 2.7.5 and I'm getting the same error message.

**Comment by ellunium** [comment]
@kathrynl16 no worries :) 

The reason it was changing back to 2.7.5 is because I didn't update the version for all languages.
My bad :) 
That's fixed now (https://github.com/utom/sketch-measure/pull/474/commits/e77002b17552090f9f022a70d345134e2665108e)

Could you please git it another try? 
Not sure this was the problem, but maybe it helped conflict with cache.

Remember to **uninstall**, **restart sketch** and then **install again**.

[Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)

**Comment by kathrynl16** [comment]
Hi @ellunium - The 2.7.6 is displayed the entire time but I'm still getting the same issue. Adding a sketch file that I get the issue with.  Thanks for working on this!
[Test for Sketch Measure.sketch.zip](https://github.com/utom/sketch-measure/files/2474743/Test.for.Sketch.Measure.sketch.zip)

**Comment by ellunium** [comment]
@kathrynl16 I could not reproduce the error, here it exports perfectly. 😕 

I tried exporting 1 page, 2 pages and everything including the symbols and everything worked.

Could you please try doing this?

- [ ] Uninstall the plugin
- [ ] Quit Sketch
- [ ] Follow the steps bellow to remove the `PluginsWarehouse` folder
- [ ] [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)
- [ ] Reinstal plugin
- [ ] Test the `Spec Expect` again

> Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> - Go to the Finder of Mac OS
> - From the “Go” menu navigate down to “Go to Folder” or...
> - Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> - Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> - Remove/Delete the `PluginsWarehouse` folder

Let me know how it goes.

**Comment by kathrynl16** [comment]
Hi @ellunium - still getting the same issue. I am on version 51.3 if that makes any difference

**Comment by kathrynl16** [comment]
@ellunium not sure what changed but it has started working! thanks for your help!
